version: '2'

services:

    web:   
        build: .
        ports:
            - "80:80"      
        volumes:
            - ./web:/var/www/html
            - ./docker/apache/conf/event_dev.conf:/etc/apache2/sites-available/app.conf
            - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini

        links:
            - db:db   
        environment:
            - ALLOW_OVERRIDE=true            
    

    db:
        image: mysql:5.5
        volumes:
            - ../var/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8082:80"
        links:
            - db:db
                 
    adminer:
        image: adminer
        restart: always
        ports:
            - 8083:8080
         
 
